### ISSUE TITLE
IndexError: only integers, ... and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by lefromage** [cod3licious/conec#1]
same issue with both test_ner.py and test_analogy.py 

python2 test_ner.py 

2017-06-10 12:12:53,888 : INFO : collecting all words and their counts
2017-06-10 12:12:53,893 : INFO : PROGRESS: at sentence #0, processed 0 words and 0 unique words
2017-06-10 12:12:55,077 : INFO : collected 17493 unique words from a corpus of 218608 words and 946 sentences
2017-06-10 12:12:55,090 : INFO : total of 17493 unique words after removing those with count < 1
2017-06-10 12:12:55,098 : INFO : constructing a huffman tree from 17493 words
2017-06-10 12:12:55,633 : INFO : built huffman tree with maximum node depth 18
2017-06-10 12:12:55,640 : INFO : constructing a table with noise distribution from 17493 words
2017-06-10 12:13:21,982 : INFO : training model on 17493 vocabulary and 200 features
Traceback (most recent call last):
  File "test_ner.py", line 346, in <module>
    train_word2vec(train_all=False, it=it, seed=seed)
  File "test_ner.py", line 68, in train_word2vec
    model = word2vec.Word2Vec(sentences, min_count=1, mtype='cbow', hs=1, neg=13, embed_dim=200, alpha=alpha, min_alpha=alpha, seed=seed)
  File "/Users/xjxr170/Downloads/conec/word2vec.py", line 81, in __init__
    self.train(sentences)
  File "/Users/xjxr170/Downloads/conec/word2vec.py", line 366, in train
    word_count += self.train_sentence_cbow(no_oov, alpha)
  File "/Users/xjxr170/Downloads/conec/word2vec.py", line 322, in train_sentence_cbow
    l2 = deepcopy(self.syn1neg[word_indices])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

python2 test_analogy.py 

2017-06-10 12:19:03,127 : INFO : collecting all words and their counts
2017-06-10 12:19:03,128 : INFO : PROGRESS: at sentence #0, processed 0 words and 0 unique words
2017-06-10 12:19:07,130 : INFO : PROGRESS: at sentence #10000, processed 10000000 words and 189074 unique words
2017-06-10 12:19:09,782 : INFO : collected 253854 unique words from a corpus of 17005207 words and 17006 sentences
2017-06-10 12:19:09,926 : INFO : total of 71290 unique words after removing those with count < 5
2017-06-10 12:19:09,972 : INFO : constructing a table with noise distribution from 71290 words
2017-06-10 12:19:36,625 : INFO : training model on 71290 vocabulary and 200 features
Traceback (most recent call last):
  File "test_analogy.py", line 290, in <module>
    main()
  File "test_analogy.py", line 230, in main
    model = word2vec.Word2Vec(sentences, mtype='cbow', hs=0, neg=13, embed_dim=200, seed=3)
  File "/Users/xjxr170/Downloads/conec/word2vec.py", line 81, in __init__
    self.train(sentences)
  File "/Users/xjxr170/Downloads/conec/word2vec.py", line 366, in train
    word_count += self.train_sentence_cbow(no_oov, alpha)
  File "/Users/xjxr170/Downloads/conec/word2vec.py", line 322, in train_sentence_cbow
    l2 = deepcopy(self.syn1neg[word_indices])
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by lefromage** [comment]
I am able to run with hs=1 and neg=0

but those results are much worse than from paper
16% instead of 42%
30% instead of 46%
but the lift from using context encoder is higher +14% instead of + 4%

capital-common-countries: 13.4% (68/506)
capital-world: 5.7% (83/1452)
currency: 1.5% (4/268)
city-in-state: 9.6% (151/1571)
family: 46.4% (142/306)
gram1-adjective-to-adverb: 4.9% (37/756)
gram2-opposite: 14.7% (45/306)
gram3-comparative: 30.0% (378/1260)
gram4-superlative: 20.9% (106/506)
gram5-present-participle: 10.9% (108/992)
gram6-nationality-adjective: 24.3% (333/1371)
gram7-past-tense: 16.2% (216/1332)
gram8-plural: 22.7% (225/992)
gram9-plural-verbs: 20.9% (136/650)
total: 16.6% (2032/12268)

capital-common-countries: 58.1% (294/506)
capital-world: 39.6% (575/1452)
currency: 11.2% (30/268)
city-in-state: 38.0% (597/1571)
family: 66.0% (202/306)
gram1-adjective-to-adverb: 8.2% (62/756)
gram2-opposite: 16.3% (50/306)
gram3-comparative: 36.8% (464/1260)
gram4-superlative: 20.6% (104/506)
gram5-present-participle: 20.0% (198/992)
gram6-nationality-adjective: 32.5% (446/1371)
gram7-past-tense: 18.7% (249/1332)
gram8-plural: 34.6% (343/992)
gram9-plural-verbs: 16.2% (105/650)
total: 30.3% (3719/12268)

**Comment by cod3licious** [comment]
hey @lefromage, so sorry i didn't reply earlier, i somehow didn't get a notification for the new issue. can you please tell me your numpy version? i think for me this was only a deprecation warning up to now but i'll definitely try to fix this the next few days, thanks!!

**Comment by cod3licious** [comment]
oh, and also considering the accuracy: when calling the analogy code as is it only trains the model for 1 iteration as i wanted to keep the main code as simple as possible and give some first results quickly. but i should probably change this to make it easier to replicate the results of the paper.

**Comment by cod3licious** [comment]
hey @lefromage : i think the error should be fixed now (and incidentally, the code might require less ram). please let me know if you're still having problems!
